manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: nice-view-glitch-rick
      url-base: https://github.com/ErikMTaylor/nice-view-glitch-rick
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: rick
      remote: nice-view-glitch-rick
      revision: main
  self:
    path: config
